### ISSUE TITLE
请问这个项目使用什么运行的呀？eclipse吗？我没太看懂怎么搭建运行这个项目，求指教

### ISSUE THREAD

**Issue by sz0918** [coderzc/biubiu#1]
请问这个项目使用什么运行的呀？eclipse吗？我没太看懂怎么搭建运行这个项目，求指教

**Comment by coderzc** [comment]
这是个maven项目，使用maven构建就好，数据库sql语句也在里面

**Comment by sz0918** [comment]
不好意思啊，我是初学者，想问一下这个maven项目是用eclipse还是IDEA构建的，麻烦你了

**Comment by coderzc** [comment]
eclipse和IDEA都可以，只是你要已maven项目导入，eclipse和IDEA都内置maven管理工具的
